language: "en-US"
reviews:
  auto_review:
    enabled: true
    ignore_labels:
      - "dependencies"
    drafts: false
  review_status: true
  poem: false
  collapse_walkthrough: false
  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
  pre_merge_checks:
    docstrings:
      mode: off
chat:
  auto_reply: true
