language: "en-US"
reviews:
  auto_review:
    enabled: true
    drafts: false
  review_status: true
  poem: false
  collapse_walkthrough: false
  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
chat:
  auto_reply: true
