[build]
  command = "npm run build"
  publish = ".next"
  ignore = "node -e \"process.exit(process.env.CONTEXT === 'deploy-preview' && process.env.HEAD.startsWith('dependabot/') ? 0 : 1)\""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SENTRY_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SENTRY_ENVIRONMENT = "staging"
